apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://192.168.49.2:8443
    certificate-authority: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MTAyNDE1NDM0NloXDTM1MTAyMzE1NDM0NlowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALtA
      oVsDj/Ut1zycYbdGrjPIRkCrgYzuYmb7YN5aU2iEz4MIt0lJA/4CTI2Y33LSWbuU
      Ldr7sbkkCuzCnHzCtxms/cVZR6u6M3s/wKJoUTEmTFEZ33SaHecffOEq9YnJARUH
      h8cfCMdtMIRFWQGLfZWdTtu9OpB7VVpD0pbmK2+FgT7Ghe3/DGKLdBurEREr+Fny
      5wytoTE4WAKwa8i2ekOG4985rgHW2/CyGtmIiGAPfjcuyQleyUUyUGyQK2kllJed
      Lii4Z/YcH9/v36Wb/aOVdzjzSes2rFwFmhCG3gdXuesAGHa16TJXIau3rOsR/AdE
      61X/iIJGbhntQmiAb7sCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBSubAtg7pAAGfnxh9p6D29xWCmzmTANBgkqhkiG9w0BAQsFAAOCAQEAIv2W/CkE
      2b0ZDeOtiPcFv2YpCvE90CKF5A/m/Of/WE+L9kMSJESzsySZ80ud/V+UlCRDRMsc
      LRUWClbfuKtw+QyvsOt0aY1bDFuIq/mAkhe+aVsjnP1PBKLA/6amutEVbBroCV0p
      19CRS5tuvt3dlFKmEYFqBcOg0XBa+Z3SRZ+tc8SViksOziAYFIGyr9ObV1b4AUFX
      YouEvrDi4hA2Pf/7ycubjAkcPBlTaVAq4grGCvuv/8JlEczXt9/NosDjpLOV5u26
      ZtFcVTkemH7aSQ26UQmKnmcTosTW8Gixm1ivVFazlyPQclmyVz9yD535q2X/Ozyo
      BJLlyf/EeJ98tg==
      -----END CERTIFICATE-----
users:
- name: minikube
  user:
    client-certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MTAyNDE1NDM0NloXDTI4MTAyNDE1NDM0NlowMTEXMBUGA1UE
      ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDyyTWEbUPkpIutg5DMugMQcr23uK2q
      LFOT3mgB+FBMVYl697X6lRTLd/RgrcuBGKAFvct9/4YnY0pCTJE7Pj2SsZbS25hX
      6i7DqhHnuRnLoWhqwmG2vW1D+Gb1gof1tcvwo5qcbaz0c3RWmP3P2EqM/2Sb1JUv
      xAqmXKjFHJyEFj2x0Xs/mfwo4xW4VaQnl04gICocCGaRpgNYxYjcmSfNGbaobinA
      opxDUjMEfF5xOQzuNA0Jix0+fXJWOLnM7ayPjVDeKzSG1Yu4gYrRqXpgE3jSKrwO
      CslVmKfP5F9YnY5E9mgKQGldT58aj2aRJa04qqTTm+FNCK085E5vSpnLAgMBAAGj
      YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
      AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSubAtg7pAAGfnxh9p6D29xWCmz
      mTANBgkqhkiG9w0BAQsFAAOCAQEAXAHLPYUBIgJQ+A4ahZG9hJbAkRo5f2uksdUA
      YCBskcXDoFMsNILrtnB3qZBdnnC68dplCbhs6VKUqnhRE05Z/jJENBN90ku8L22Z
      OzG7k7/PeJeJGUevZY4mCthONN9PZRNTrxj1QJBTJlVxwAXrgsEdUoNzxIBsSPjg
      2H4xlDZe62U0mgkCdqldR/YZ/h+aHGV1QyX07dHxSBQc5R7k7+UXXDg2EWxTdFXp
      cEF9MO4zP2SY0VF2xd4GkfJ/qHaltRZKvz0w5Uzdlvz6FF75MBreenNTBi+T0o9T
      rT83zOMoACGDKd5+N+hM3ZPzXbodua72oaEZzu99aD10KqfxjA==
      -----END CERTIFICATE-----
    client-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA8sk1hG1D5KSLrYOQzLoDEHK9t7itqixTk95oAfhQTFWJeve1
      +pUUy3f0YK3LgRigBb3Lff+GJ2NKQkyROz49krGW0tuYV+ouw6oR57kZy6FoasJh
      tr1tQ/hm9YKH9bXL8KOanG2s9HN0Vpj9z9hKjP9km9SVL8QKplyoxRychBY9sdF7
      P5n8KOMVuFWkJ5dOICAqHAhmkaYDWMWI3JknzRm2qG4pwKKcQ1IzBHxecTkM7jQN
      CYsdPn1yVji5zO2sj41Q3is0htWLuIGK0al6YBN40iq8DgrJVZinz+RfWJ2ORPZo
      CkBpXU+fGo9mkSWtOKqk05vhTQitPOROb0qZywIDAQABAoIBAD1CN5aqWy8dtYCa
      aba+WHeV+/iXSHpfpNbyjxuwI9Ke4ol8ZxZK92w/YBHkyCxSok3Qjb/E8XyOuPXx
      i9N+6NpSpNOfRNkp5ZLJHqtxMOkIWOhXE4CgWymDS7c2sEd3D3YwUZqWscUcPIZ9
      I82FrYnWBvSqttnOhUFkr9DMX1GULT2BkJ+2Iq7d24j7PkRGizrH25o0bOxq9M25
      1ohS0xJxWpnoBzXvxdcI1FqT9rTVVRE3tIzaggOVGbeqzNm9QOwc25P119LslEvq
      JtGTGUsc7Th/h+YiY885RiDU4X5rZD9oGgezTWj/WrLFHg9U1T39u1/BlfgEOjrv
      gHlkf0ECgYEA+FDmoadM6TsiQC5RgnRJy7NhywBlDJ2t/zQJIKe/8REtnRDigDVZ
      q7QTwvRMPGSw106HXWlYQyImdPaEv1kxOzSzL2ClSyXHRtb0L63QXjFJLXRHajOz
      6jnYwOcDXYuUD09mg4D49r4bYzNwTbKOjveBzYi9KGLPNZRZMKnSnaUCgYEA+kyA
      Ho9nK1+wE7r0ySeGPaq+xKJDgROtMPeNJ2Yew/dtExnrgXKngN1KZho3DHyOAEQy
      2emIc1gMuJAPEA5FAlz97bU76fyLXuHS6v9ISKxHYPTpoUcLij7YN8B0+RSMHhB+
      iAXKZyk5YObAtbhGi1LS/bmjzfHehqhE1wnhnq8CgYEAmE7XB7RcYnpY6dD/Qese
      EIm4pBFb6b8VqIE8UAFUpAKLXdmrdERE+iJ8NIov8KM6LPYH5W3mK1dZC0jh55RH
      tC8A8UBwYoWLk5HpOQ19zyif3/eAjk2kPzi4EKoh0FD6weFL2cFT89RrbA9zBNVO
      x7Zcsbr7ezgQLKcPhd/ERdkCgYEA04e3dxxGWpehnOsRWLa4coFMe62OUxWn9owf
      lL5vHbqLSetL5rhY60UZTTS2dS0GbR81wofks2YkSg4lTLJii96/ExdpLRQrTOKY
      d9WK5zABmuUgVRZPoGQAIw3ZTW+aAwZ5iMcsCQcD4OrizjCQHcq/WYJ79t6D61Vl
      6D4HmS0CgYEAky2B4IeCj+XV5FV/+ISgbx+GvZZzKOXnqlqDMEdxP5YYxU8ME6fP
      F46vm5O1EFl40w9BKvZbaTaAnufqySvKgnKqNKAixOJ0WmftzxbcQL22xwGxwacB
      WZKevjRg/kpf6YflL52oNzPJJiTcIbaSOpQltLLW6cXsG617wL+w+KQ=
      -----END RSA PRIVATE KEY-----
contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
current-context: minikube