apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: ecommerce
data:
  EUREKA_SERVER_URL: "http://service-discovery-service:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-config
  namespace: ecommerce
data:
  ZIPKIN_BASE_URL: "http://zipkin-service:9411"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: ecommerce
data:
  CONFIG_SERVER_URL: "http://cloud-config-service:9296"
